services:
  ingress:
    image: ingress
    build:
      context: ./build/nginx
    ports:
      - ${BIND_PORT:-3000}:80
    depends_on:
      - api
      - web
  web:
    image: web
    build:
      context: .
      dockerfile: ./build/web/Dockerfile
    environment:
      PORT: 3000
  api:
    image: api
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    environment:
      NODE_ENV: production
      BIND_PORT: 3000
    volumes:
      - api_data:/app/data
volumes:
  api_data: {}